server:
  port: 8881


spring:
  datasource:
    url: jdbc:h2:file:~/test;DB_CLOSE_ON_EXIT=FALSE
    username: test
    password: test
    driverClassName: org.h2.Driver
    port: 9991
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
